export component Icon inherits Rectangle {
    in property <image> source;
    callback clicked();//关闭
    in property <brush> colorize;

    width: 14px;

    HorizontalLayout {
        alignment: center;

        VerticalLayout {
            alignment: center;
            Image {
                width: root.width;
                height: root.width;
                source: root.source;
                colorize: root.colorize;
            }
        }
    }

    TouchArea {
//        x: 8px;
//        y: 30px;
        mouse-cursor: pointer;

        clicked => {
            root.clicked();
        }
    }
}
