import { top_menu } from "top_menu.slint";
import { GlobalCallBack,AppConfig }  from "global.slint";
export { GlobalCallBack,AppConfig }

export component MainWindow inherits Window {
    min-width: 1280px;
    min-height: 720px;

    background: transparent;
    icon: @image-url("../images/8666681_edit_icon.png");
    no-frame: true; // 取消自带窗口标题栏

    // 主窗口容器
    window := Rectangle {
        background: #fff;

        VerticalLayout {
            padding: 0;
            spacing: 0;

            top_menu {
                drag_window(x, y) => {
                    GlobalCallBack.drag_window(x, y)
                }
            }

            // 内容区域
            content := Rectangle {

            }
        }
    }
}
